# Generated by Django 4.2.9 on 2024-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "data_atualizado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da aplicação"
                    ),
                ),
                ("produto", models.CharField(max_length=50, verbose_name="Produto")),
                ("codigo", models.IntegerField(verbose_name="Codigo")),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
