# Generated by Django 4.2.9 on 2024-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_fichacampo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichacampo",
            name="data_atualizado",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Data de modificação"
            ),
        ),
    ]
