# Generated by Django 4.2.9 on 2024-02-09 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_alter_fichacampo_data_atualizado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichacampo",
            old_name="totalArea",
            new_name="totalarea",
        ),
        migrations.RenameField(
            model_name="fichacampo",
            old_name="totalAreaAp",
            new_name="totalareaap",
        ),
        migrations.RenameField(
            model_name="fichacampo",
            old_name="totalCalda",
            new_name="totalcalda",
        ),
    ]
